version: "3.4"
services:
  hazelcast-management-center:
    image: 'hazelcast/management-center:5.3.2'
    hostname: hazelcast-management-center
    ports:
      - '5700:8080'
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - hazelcast-network
  hazelcast-node-1:
    image: 'hazelcast/hazelcast:5.3.2'
    hostname: hazelcast-node-1
    ports:
      - '5701:5701'
    environment:
      - HZ_NETWORK_PUBLICADDRESS=host.docker.internal:5701
      - HZ_CLUSTERNAME=hello-world
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - hazelcast-network
  hazelcast-node-2:
    image: 'hazelcast/hazelcast:5.3.2'
    hostname: hazelcast-node-2
    ports:
      - '5702:5701'
    environment:
      - HZ_NETWORK_PUBLICADDRESS=host.docker.internal:5702
      - HZ_CLUSTERNAME=hello-world
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
