version: "3.4"
services:
  hazelcast-management-center:
    image: 'hazelcast/management-center:5.3.2'
    hostname: hazelcast-management-center
    ports:
      - '5700:8080'
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g